[phases.setup]
nixPkgs = ["nodejs", "chromium", "cacert"]

[phases.build]
cmds = ["npm install"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
